version: '3'

services:

  api:
    build: .
    image: api
    ports:
      - "80:80"
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/var/log/gunicorn

  celery:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - redis

  postgres:
    image: postgres:10.17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - arcticfox_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  arcticfox_data:
