services:

  api:
    build: .
    image: api
    ports:
      - "80:80"
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/var/log/gunicorn

  celery:
    build: .
    image: celery
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/var/log/celery
    command: celery -A arcticfox worker -l info

  postgres:
    image: postgres:10.17
    restart: always
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - arcticfox_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  arcticfox_data:
