# For API Heroku deployment
FROM python:3.10-alpine

LABEL maintainer="Haki-Malai" email="hakimalaj@outlook.com"

WORKDIR /arcticfox

COPY . .

RUN pip install -r requirements.txt

RUN flask --app index script fake

CMD ["gunicorn", "index:app"]