# For API Heroku deployment
FROM python:3.8.10

LABEL maintainer="Haki-Malai" email="hakimalaj@outlook.com"

WORKDIR /arcticfox

COPY . .

RUN pip install -r requirements.txt

CMD ["gunicorn", "index:app"]