"""empty message

Revision ID: dc43a9283f40
Revises: 
Create Date: 2024-03-30 22:17:04.530272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc43a9283f40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_user_associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_user_associations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MODERATOR', 'VIEWER', name='folderrole'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name='folder_user_associations_folder_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='folder_user_associations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='folder_user_associations_pkey'),
    sa.UniqueConstraint('folder_id', 'user_id', 'role', name='_folder_user_role_uc')
    )
    # ### end Alembic commands ###
