# Build the react-native web app
FROM node:16.0.0-alpine as web-build
LABEL maintainer="Haki-Malai" email="hakimalaj@outlook.com"
WORKDIR /arcticfox
ENV PATH /arcticfox/node_modules/.bin:$PATH
COPY frontend .
RUN npm install --force

ARG API_URL='/api'
ENV API_URL=$API_URL
RUN npx expo export:web

# Build an nginx container
FROM nginx:stable-alpine
COPY --from=web-build /arcticfox/web-build /usr/share/nginx/html
COPY local-deploy/nginx.default.conf /etc/nginx/conf.d/default.conf