name: Deploy to AWS EC2

on:
  push:
    branches:
      - development
      - main
  workflow_dispatch:
  #workflow_run:
    #workflows: ["PyTest"]
    #types:
    #  - completed
    #branches:
    # - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/development' ||
      (github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event_name == 'workflow_run')))
    steps:
      - name: Add Sensitive Variables to .env
        run: |
          echo "AF_ALCHEMICAL_ECHO=false" > .env
          echo "AF_ALCHEMICAL_DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/arcticfox" >> .env
          echo "AF_SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "AF_DISABLE_AUTH=false" >> .env
          echo "AF_ACCESS_TOKEN_MINUTES=15" >> .env
          echo "AF_REFRESH_TOKEN_DAYS=30" >> .env
          echo "AF_CACHE_TYPE=redis" >> .env
          echo "AF_REDIS_URL=redis://${{ secrets.REDIS_HOST }}:6379/0" >> .env
          echo "AF_AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AF_AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
          echo "AF_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AF_AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AF_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "AF_GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "AF_GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
          echo "AF_APIFAIRY_TITLE=Arctic Fox API" >> .env
          echo "AF_APIFAIRY_VERSION=1.0" >> .env
          echo "AF_APIFAIRY_UI=swagger_ui" >> .env
          echo "AF_APIFAIRY_UI_PATH=/api" >> .env
          echo "AF_MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "AF_MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "AF_MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}" >> .env
          echo "AF_MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "AF_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "AF_MAIL_DEFAULT_SENDER=${{ secrets.MAIL_DEFAULT_SENDER }}" >> .env
          echo "AF_ADMIN_EMAIL=hakimalai@outlook.com" >> .env
          echo "AF_ERROR_EMAIL=${{ secrets.ERROR_EMAIL }}" >> .env
          echo "OAUTHLIB_INSECURE_TRANSPORT=true" >> .env
          echo "DOCKER_DB_NAME=arcticfox" >> .env
          echo "DOCKER_DB_PORT=5432" >> .env
          echo "DOCKER_DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DOCKER_DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: SSH and Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

          eval "$(ssh-agent -s)"
          echo "${{ secrets.SERVER_SSH_KEY }}" > ssh_key
          tr -d '\r' < ssh_key | ssh-add -
          rm ssh_key

          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

          scp -v .env $EC2_USER@$EC2_HOST:~/arctic-fox/

          ssh -v -tt $EC2_USER@$EC2_HOST << EOF
            set -e
            cd arctic-fox
            git checkout main && git pull
            docker compose up -d --build
            exit
          EOF
