name: Deploy to AWS EC2

on:
  push:
    branches:
      - development
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["PyTest"]
    types:
      - completed
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/development' ||
      (github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event_name == 'workflow_run')))
    steps:
      - name: Add Sensitive Variables to .dockenv
        run: |
          echo "AF_ALCHEMICAL_ECHO=false" > .dockenv
          echo "AF_ALCHEMICAL_DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/arcticfox" >> .dockenv
          echo "AF_SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .dockenv
          echo "AF_DISABLE_AUTH=false" >> .dockenv
          echo "AF_ACCESS_TOKEN_MINUTES=15" >> .dockenv
          echo "AF_REFRESH_TOKEN_DAYS=30" >> .dockenv
          echo "AF_CACHE_TYPE=redis" >> .dockenv
          echo "AF_REDIS_URL=redis://${{ secrets.REDIS_HOST }}:6379/0" >> .dockenv
          echo "AF_AWS_REGION=${{ secrets.AWS_REGION }}" >> .dockenv
          echo "AF_AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .dockenv
          echo "AF_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .dockenv
          echo "AF_AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .dockenv
          echo "AF_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .dockenv
          echo "AF_GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .dockenv
          echo "AF_GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .dockenv
          echo "AF_APIFAIRY_TITLE=Arctic Fox API" >> .dockenv
          echo "AF_APIFAIRY_VERSION=1.0" >> .dockenv
          echo "AF_APIFAIRY_UI=swagger_ui" >> .dockenv
          echo "AF_APIFAIRY_UI_PATH=/api" >> .dockenv
          echo "AF_MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .dockenv
          echo "AF_MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .dockenv
          echo "AF_MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}" >> .dockenv
          echo "AF_MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .dockenv
          echo "AF_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .dockenv
          echo "AF_MAIL_DEFAULT_SENDER=${{ secrets.MAIL_DEFAULT_SENDER }}" >> .dockenv
          echo "AF_ADMIN_EMAIL=hakimalai@outlook.com" >> .dockenv
          echo "AF_ERROR_EMAIL=${{ secrets.ERROR_EMAIL }}" >> .dockenv
          echo "OAUTHLIB_INSECURE_TRANSPORT=true" >> .dockenv
          echo "DOCKER_DB_NAME=arcticfox" >> .dockenv
          echo "DOCKER_DB_PORT=5432" >> .dockenv
          echo "DOCKER_DB_USER=${{ secrets.DB_USER }}" >> .dockenv
          echo "DOCKER_DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .dockenv

      - name: SSH and Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" --exclude='.git/' --exclude='node_modules/' .dockenv ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/arctic-fox/
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd ~/arctic-fox && docker compose up -d --build"
