name: 'Netlify Deploy'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: ./frontend
        run: npm install --force

      - name: Build
        working-directory: ./frontend
        run: npx expo export:web

      - name: Deploy
        working-directory: ./frontend
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir web-build --prod