name: 'Netlify Deploy'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        working-directory: ./frontend
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir web-build